spring:
  application:
    name: auth-service
server:
  port: 9000
oauth-client-id: "gridmarket-public-client"
management:
  metrics:
    distribution:
      percentiles:
        http.server.requests:
          - 0.5
          - 0.90
          - 0.99
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: [ 'prometheus', 'health' ]