base-path: "http://localhost:8080"
spring:
  cloud:
    gcp:
      pubsub:
        project-id: gridmarket-dev
        emulator-host: pub-sub:8085
  sql:
    init:
      separator: "@@"
      mode: always
  datasource:
    url: jdbc:postgresql://application-db:5432/gridmarket
    username: grid
    password: grid
logging:
  level:
    root: DEBUG