spring:
  application:
    name: application-service
management:
  metrics:
    distribution:
      percentiles:
        http.server.requests:
          - 0.5
          - 0.90
          - 0.99
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: [ 'prometheus', 'health' ]
springdoc:
  api-docs:
    path: /application/v3/api-docs