management:
  metrics:
    distribution:
      percentiles:
        http.server.requests:
          - 0.5
          - 0.75
          - 0.95
          - 0.99
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: [ 'prometheus', 'health' ]