name: gridmarket-dev
services:
  gateway-service:
    image: eclipse-temurin:21
    volumes:
      - ./gateway-service:/app
      - ${HOME}/.m2:/root/.m2
    ports:
      - 8080:8080
    working_dir: /app
    networks:
      - service-net
    command: ./gradlew bootRun --args=--spring.profiles.active=dev
  application-service:
    image: eclipse-temurin:21
    volumes:
      - ./application-service:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - application-db
    networks:
      - service-net
      - application-net
    command: ./gradlew bootRun --args=--spring.profiles.active=dev
  application-db:
    image: postgres:16.3-alpine
    volumes:
      - "./.data/application/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: gridmarket
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid
    networks:
      - application-net
  user-service:
    image: eclipse-temurin:21
    volumes:
      - ./user-service:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - user-db
    networks:
      - service-net
      - user-net
    command: ./gradlew bootRun --args=--spring.profiles.active=dev
  user-db:
    image: postgres:16.3-alpine
    volumes:
      - "./.data/user/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: gridmarket
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid
    networks:
      - user-net
  order-service:
    image: cosmtrek/air
    volumes:
      - ./order-service:/app
    environment:
      DATABASE_URL: postgres://grid:grid@order-db:5432/gridmarket
    working_dir: /app
    depends_on:
      - order-db
    networks:
      - service-net
      - order-net
  order-db:
    image: postgres:16.3-alpine
    volumes:
      - "./.data/order/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: gridmarket
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid
    networks:
      - order-net
  auth-service:
    image: eclipse-temurin:21
    volumes:
      - ./auth-service:/app
      - ${HOME}/.m2:/root/.m2
    working_dir: /app
    depends_on:
      - auth-db
    ports:
      - 9000:9000
    networks:
      - service-net
      - auth-net
    command: ./gradlew bootRun --args=--spring.profiles.active=dev
  auth-db:
    image: postgres:16.3-alpine
    volumes:
      - "./.data/auth/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: gridmarket
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid
    networks:
      - auth-net
  pub-sub:
    image: google/cloud-sdk:emulators
    volumes:
      - ./python-pubsub:/pubsub
      - ./scripts/pubsub-init.sh:/init.sh
    command: ./init.sh
    networks:
      - service-net
networks:
  service-net:
  application-net:
  user-net:
  order-net:
  auth-net: