global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "application_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "application-service:8080" ]
        labels:
          application: "GridMarket Application service"
  - job_name: "user_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "user-service:8080" ]
        labels:
          application: "GridMarket User service"
  - job_name: "auth_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "auth-service:9000" ]
        labels:
          application: "GridMarket Auth service"
  - job_name: "gateway_service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "gateway-service:8080" ]
        labels:
          application: "GridMarket Gateway service"
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
