definitions:
  model.OrderRequest:
    properties:
      application:
        type: integer
      method:
        enum:
        - 0
        - 1
        type: integer
      user:
        type: integer
    required:
    - application
    - method
    - user
    type: object
info:
  contact: {}
  description: Order-service api documentation
  title: GridMarket
  version: "1.0"
paths:
  /v1/orders/:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Returns hello
      tags:
      - Order
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OrderRequest'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create a new order
      tags:
      - Order
swagger: "2.0"
