spring:
  cloud:
    gcp:
      pubsub:
        project-id: gridmarket-dev
        emulator-host: pub-sub:8085
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://user-db:5432/gridmarket
    username: grid
    password: grid
logging:
  level:
    root: DEBUG