name: GridMarket GCP deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Setup version
        run: echo "GM_VERSION=$(echo ${{ github.ref }} | cut -c 11-)" >> $GITHUB_ENV

      - name: Test
        run: echo $GM_VERSION